version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3050:3050'
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3050
    volumes:
      - ./sserver/uploads:/app/uploads
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    ports:
      - '3000:3000'
    networks:
      - app-network
    environment:
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - NODE_ENV=production
      - PORT=3000
    restart: always

networks:
  app-network:
    driver: bridge
